PAY-38172 Add the CardPay response status for charge back request
paysuper/paysuper-proto pull request #152
Opened 2022-01-11 11:34 UTC by pr0head

2022-01-13 09:28 UTC, EvgeniyStrigo requested changes

2022-01-13 09:28 UTC, EvgeniyStrigo commented on go/billingpb/constant.go
> +	CardPayPaymentResponseStatusChargedBack = "CHARGED_BACK"
Тут не хватает еще статуса chargeback_resolved, мы его все-таки будем поддерживать тоже

2022-02-22 20:39 UTC, EvgeniyStrigo requested changes

2022-02-22 20:39 UTC, EvgeniyStrigo commented on go/billingpb/billing_entity.go
> +		CardPayPaymentResponseStatusChargedBack:        true,
Вадик, тут что-то не так, мне кажется.
Этот массив у нас ниже используется в функциях IsPaymentAllowedStatus() и IsRefundAllowedStatus()
И какой-же пеймент, или рефанд, возможен в статусе CardPayPaymentResponseStatusChargedBack, например?
Ну, рефанд в статусе CardPayPaymentResponseStatusChargeBackResolved я еще могу хотя бы представить, но опять же, платеж нет. Проверь, пожалуйста, использование этих функций по коду, в каких условиях они проверяются? Возможно тут надо разделить на отдельные наборы статусов для платежа и для рефанда? Или вообще не трогать эту переменную и оставить как было, и хуй с ним, с рефандом после резолва ч/б, вероятность этого сценария я оцениваю как практически нулевую )

2022-02-23 06:38 UTC, pr0head commented on go/billingpb/billing_entity.go
> +		CardPayPaymentResponseStatusChargedBack:        true,
Там вообще много вопросов с этими статусами))
Например в их документации это просто справочник который кочует из запроса в запрос. Например все те же статусы прописаны как возможные для чаржбэка - https://integration.unlimint.com/#RefundResponseRefundData
> Ну, рефанд в статусе CardPayPaymentResponseStatusChargeBackResolved я еще могу хотя бы представить, но опять же, платеж нет.
Самое забавное, что нам запрос на чаржбэк (статус charged_back) пришел на эндпоинт который отвечает за платежи, а не за рефанды. Чтобы тут не оставлять данные платежного запроса, можешь проверить в слаке ЛС, я тебе 11 января присылал лог с прода когда нам чаржбэк прилетел.

2022-02-28 08:11 UTC, merged